name: 'Deploy'

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: "flipperdevices/flipper-update-indexer"

jobs:
  build:
    runs-on: [self-hosted,FlipperZeroShell]
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Set image tag'
        id: tag
        run: |
          REF=${{ github.ref }};
          TAG_FULL=${REF#refs/*/};
          IMAGE_TAG=${TAG_FULL//\//_};
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: 'Build docker image'
        run: |
          docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" .

      - name: 'Upload docker image'
        run: |
          docker push "$IMAGE_NAME:$IMAGE_TAG"
